// console.log("Hello JS");

// const a=12;
// if(a>10){
//    let b=23;
//    a=40;
//     console.log("a="+a);
// }
// console.log("Hi, b="+b);

// function fun(a,b,c=10){
//     console.log("heeee");
//     return a+b+c;
// }
// let data=fun(12,5);
// console.log(data);




// function selectlanguage(language="no compiler selected"){
//     let data=language;

//     if(language=='c')
//     {
//     function cCompiler(){
//         return "C Compiler";
//       }
//       data=cCompiler();
//     }
//     if(language=="java")
//     {
//       function javaCompiler(){
//             return "Java Compiler";
//       }
//        data=javaCompiler();
//     }
// return data;
// }
//  const result=selectlanguage("java");
//  console.log(result);

// const div=document.getElementsByTagName("div");
// console.dir(div);
// div[0].innerText='Text added by dom';

//  const div=document.getElementsByClassName("parent");
//  console.log(div);
// div[0].innerHTML="<h2 style=color:red>Hello World</h2>";
// const h1=document.createElement("h1");
// h1.innerText="This is generated by DOM";
// h1.style.backgroundColor='cyan';
// console.log(h1);
// div[0].appendChild(h1);
// const img=document.createElement('img');

// img.src='./abeslogo.png';

// img.setAttribute("height","200");

// console.log(img);

// div[0].appendChild(img);
//            const btn=document.getElementById("btn");
// const disp=document.getElementById("disp");
// console.dir(disp);
// function getData(){
//     console.log("Getdata Called");
//     disp.innerHTML="<h2>Hello, You have Called getData</h2>";
// }
// btn.addEventListener("click",getData);

const promise=new promise((resolve,reject)=>
{
let a=12;
if(a>10){
    resolve("Resolved");
}
else{
    reject("rejected");
}

}
);

promise.then((msg)=>console.log(msg))
.catch(error=>console.log(error))